- name: "Installing Webserver Software"
  apt:
    pkg: ['apache2']
    state: absent

# - name: "Enabling proxy module"
#   apache2_module: name=proxy_http

# - name: "Adding proxy configuration"
#   template:
#     src: ../files/proxy.conf
#     dest: /etc/apache2/conf-available
#     owner: root
#     group: root
#     mode: 0644
#   notify:
#     - enable-proxy-config