galaxy_info:
  author: Tibor Kulcsar Dr.
  description: An Ansible role to install MongoDB

  license: license (MIT)

  min_ansible_version: 2.5

  platforms:
  - name: Ubuntu
    versions:
    - xenial
    - bionic

  galaxy_tags:
    - nosql
